version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: chatnormas
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - DB_HOST=pgvector_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=normativos
      - DB_SCHEMA=public
      - DB_TABLE=normativos_cnj_bgem3
    networks:
      - app-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.normativos.rule=Host(`${HOST_URL}`) && PathPrefix(`/${APP_NAME}`)"
      - "traefik.http.routers.normativos.entrypoints=https" # <--- CORRIGIDO
      - "traefik.http.routers.normativos.tls=true"
      - "traefik.http.routers.normativos.service=normativos-service"
      - "traefik.http.services.normativos-service.loadbalancer.server.port=8002"

networks:
  app-network:
    external: true
    name: app-network
  traefik:
    external: true
    name: traefik
