version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: chatnormas
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - DB_HOST=pgvector_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=normativos
      - DB_SCHEMA=public
      - DB_TABLE=normativos_cnj_bgem3
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
