services:
  pgvector_db:
    image: pgvector/pgvector:pg15
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: normativos
    ports:
      - "5433:5432"
    # Volume comentado para sempre subir do zero
    # Se vocÃª quiser persistir, descomente a linha abaixo
    # volumes:
    #   - pgvector_data:/var/lib/postgresql/data
