version: "3.8"

services:
  pgvector_db:
    image: pgvector/pgvector:pg15
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: normativos
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
